### ISSUE TITLE
연령제한이 있는지요?

### ISSUE THREAD

**Issue by callin2** [pawco-sinclair/recruit#2]
안녕하세요.
올려주신글 잘 읽었습니다. 

저는 마늘랩이라는 회사에서 여러가지 업무를 하고있는 임창진 이라고 합니다. 
현재 이직을 생각하고 있습니다.
제이력 역시 Github 에 올려져 있습니다.
https://github.com/callin2/resume/blob/master/README.md

글 속에서 저랑 비슷한 고민들이 느껴져서 좋았습니다. 
이직여부를 떠나 만나서 이야기 나누면 즐거울것 같습니다.

**Comment by pawco-sinclair** [comment]
첫번째로 문의를 주셨네요! 고맙습니다^^

GitHub에 채용 공고를 올리는 것도 좀 걱정했었는데, resume을 올리시는 분도 있다는 것을 알고나니 마음이 좀 놓이네요 ㅎㅎ

사실 연령에 특별한 제한을 두고 있지는 않습니다만... 경험상 제 위로 오시는 것이 아닌 이상은 저보다는 어려야 하지 않을까 하고 생각하고 있습니다(저는 98학번이예요)ㅠㅠ

물론 이로인해 훌륭한 인재를 놓칠 수도 있겠지만 아직은 세팅 초기이고 문화를 만들고 정착시켜야 하는 단계이다보니, 그런 판단을 하게 되었습니다. 이해를 부탁드릴께요.

90학번이시면 우리나라 인터넷 1세대 개발자이시네요. 말씀 주신 것 처럼 이직여부를 떠나 함께 이야기를 나눈다면 제가 배울 점이 많을 것 같습니다.

언제든 시간 내어 주셔서 같이 차 한잔하면 좋을 것 같아요!!
