### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by cberio** [pawco-sinclair/recruit#3]
안녕하세요 구직사이트를 보다 우연히 발견하게 되어 여기까지 오게 되었습니다.
우선 본문에 작성하신것 처럼 구직사이트의 딱딱한 양식 보다 이렇게 작성해 놓으신게 뭔가 더 개발자에겐 더 신뢰가 가는 것 같습니다.

저는 SI, 웹 에이전시에서 주로 classic asp를사용하였고 java(spring)를 약간 사용해 보았습니다.
어떤 기술을 왜 도입했으며 앞으로 어떤것이 필요하다 식의 설명이 체계적이고 계획 적으로 운영하시는 듯 하여, 현재 구성되어있는 개발환경과 상이한 경력임에도 이력서를 제출했습니다.

부디 좋은 인연으로 연결되었으면 좋겠습니다.

**Comment by pawco-sinclair** [comment]
안녕하세요! 반갑습니다.

구인 서비스에 올라온 이력서가 다수 있어서 cberio님께서 보내주신 이력서가 어떤 것인지 알기가 어렵네요 :)

성함을 알려 주시거나 제 이메일(sinclair@powderroom.co.kr)로 이력서를 보내주시면 검토 후 연락 드리겠습니다!

고맙습니다^^

**Comment by cberio** [comment]
아!! 이런 죄송합니다.
제 인적사항을 적질 않았네요 ㅜㅜ
제 이름은 장원석 입니다.

곧 점심시간 인데 맛점 하시길 바랍니다 😁

2015년 10월 1일 오전 10:37, Seong Kyoon Kim <notifications@github.com>님이 작성:

**Comment by pawco-sinclair** [comment]
확인 되었습니다. 고맙습니다^^

메일로 회신 드릴께요~
